# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
              with: 
                repository: sathish-washmen/workspaces-demo
                submodules: 'recursive'
                path: '.'
            #- name: Checkout submodules
            #  run: git submodule update --init --recursive
             # run: |
             #   git submodule init service-one shared-libs
             #   git submodule update
             #   git submodule foreach git checkout main
             #   git submodule foreach git pull origin main
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: go to service-one and run node file
              run: |
                ls
                cd service-one
                pwd
                yarn install
                node src/index.js
